#!/bin/sh

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

# Create any missing keys
/usr/bin/ssh-keygen -A

case "$1" in
    start)
        echo "Starting SSH Server..."
        /usr/bin/ssh-keygen -A
        sleep 1
        /usr/sbin/sshd -D -e
        ;;

    stop)
        echo "Stopping SSH Server..."
        /usr/sbin/sshd
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

# End sshd bootscript
